M48
; DRILL file KiCad 10.0.6-1.fc44app2 date 2026-10-06T11:56:40
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-06T11:56:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-1.fc44app2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X104.0Y-104.0
X104.0Y-162.0
X176.0Y-104.0
X176.0Y-162.0
M30
