#ifndef GOODJOHN_HID_KEYS_H
#define GOODJOHN_HID_KEYS_H

/* USB HID Usage Tables, Keyboard/Keypad page 0x07. Kept SDK-independent. */
enum {
    KEY_NONE = 0, KEY_ROLLOVER = 1,
    KEY_A = 4, KEY_B, KEY_C, KEY_D, KEY_E, KEY_F, KEY_G, KEY_H, KEY_I,
    KEY_J, KEY_K, KEY_L, KEY_M, KEY_N, KEY_O, KEY_P, KEY_Q, KEY_R,
    KEY_S, KEY_T, KEY_U, KEY_V, KEY_W, KEY_X, KEY_Y, KEY_Z,
    KEY_1 = 30, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0,
    KEY_ENTER = 40, KEY_ESCAPE, KEY_BACKSPACE, KEY_TAB, KEY_SPACE,
    KEY_MINUS, KEY_EQUAL, KEY_LEFT_BRACKET, KEY_RIGHT_BRACKET, KEY_BACKSLASH,
    KEY_SEMICOLON = 51, KEY_APOSTROPHE, KEY_GRAVE, KEY_COMMA, KEY_PERIOD,
    KEY_SLASH, KEY_CAPS_LOCK,
    KEY_DELETE = 76,
    KEY_RIGHT = 79, KEY_LEFT, KEY_DOWN, KEY_UP,
    KEY_KP_ENTER = 88, KEY_KP_1, KEY_KP_2, KEY_KP_3, KEY_KP_4, KEY_KP_5,
    KEY_KP_6, KEY_KP_7, KEY_KP_8, KEY_KP_9, KEY_KP_0, KEY_KP_PERIOD,
    KEY_LEFT_CTRL = 224, KEY_LEFT_SHIFT, KEY_LEFT_ALT, KEY_LEFT_GUI,
    KEY_RIGHT_CTRL, KEY_RIGHT_SHIFT, KEY_RIGHT_ALT, KEY_RIGHT_GUI
};

#endif
